from cyborg.agents.simple_agents.base_agent import BaseAgent
from cyborg.agents.simple_agents.sleep_agent import SleepAgent
from cyborg.agents.simple_agents.b_line import B_lineAgent
from cyborg.agents.simple_agents.meander import RedMeanderAgent
from cyborg.agents.simple_agents.green_agent import GreenAgent
from cyborg.agents.simple_agents.TestFlatFixed import TestFlatFixedAgent
from cyborg.agents.simple_agents.BlueReactAgent import BlueReactRemoveAgent,BlueReactRestoreAgent
from cyborg.agents.simple_agents.keyboard_agent import KeyboardAgent
from .simple_agents.TestAgent import TestAgent
from .simple_agents.HeuristicRed import HeuristicRed
from .simple_agents.DebuggingAgent import DebuggingAgent
from .simple_agents.BlueMonitorAgent import BlueMonitorAgent
