from cyborg.agents.SimpleAgents.BaseAgent import BaseAgent
from cyborg.agents.SimpleAgents.SleepAgent import SleepAgent
from cyborg.agents.SimpleAgents.B_line import B_lineAgent
from cyborg.agents.SimpleAgents.Meander import RedMeanderAgent
from cyborg.agents.SimpleAgents.GreenAgent import GreenAgent
from cyborg.agents.SimpleAgents.TestFlatFixed import TestFlatFixedAgent
from cyborg.agents.SimpleAgents.BlueReactAgent import BlueReactRemoveAgent,BlueReactRestoreAgent
from cyborg.agents.SimpleAgents.KeyboardAgent import KeyboardAgent
from .SimpleAgents.TestAgent import TestAgent
from .SimpleAgents.HeuristicRed import HeuristicRed
from .SimpleAgents.DebuggingAgent import DebuggingAgent
from .SimpleAgents.BlueMonitorAgent import BlueMonitorAgent
